server:
  port: 8081

cloud:
  db-host: localhost
  twelvedata-apikey: 97677735327f42f8a065a0a5f5949f40

spring:
  application:
    name: bank-limit-system
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${cloud.db-host}:5432/bank_limit_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://${cloud.db-host}:5432/bank_limit_system
    user: postgres
    password: postgres